IF DB_ID('QLSV') IS NOT NULL
	DROP DATABASE QLSV 
GO
CREATE DATABASE QLSV
GO
USE QLSV
CREATE TABLE SINHVIEN
(
	MSSV CHAR(10),
	HOTEN NVARCHAR(30),
	GIOITINH NVARCHAR(10),
	CMND CHAR(10),
	MALOP CHAR(10)
	CONSTRAINT PK_SINHVIEN
	PRIMARY KEY(MSSV)
)

CREATE TABLE  TKB
(
	MALOP CHAR(10),
	MAMON CHAR(10),
	TENMON NVARCHAR(30),
	PHONGHOC CHAR(10),
	CONSTRAINT PK_TKB
	PRIMARY KEY(MALOP,MAMON)
)
CREATE TABLE LOP_DSSV
(
	MALOP CHAR(10),
	MAMON CHAR(10),
	MSSV CHAR(10),
	DGK INT,
	DCK INT,
	DKHAC INT,
	DTONG FLOAT
	CONSTRAINT PK_LOP_DSSV
	PRIMARY KEY(MALOP,MAMON,MSSV)
)
CREATE TABLE TK
(
	MSSV CHAR(10),
	MK CHAR(10),
	PRIMARY KEY(MSSV)
)