package entities;
// Generated Jun 18, 2020 10:24:37 PM by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * SinhVien generated by hbm2java
 */
public class SinhVien  implements java.io.Serializable {


     private int stt;
     private String mssv;
     private Serializable hoten;
     private Serializable gioitinh;
     private String cmnd;
     private String malop;

    public SinhVien() {
    }

	
    public SinhVien(int stt) {
        this.stt = stt;
    }
    public SinhVien(int stt, String mssv, Serializable hoten, Serializable gioitinh, String cmnd, String malop) {
       this.stt = stt;
       this.mssv = mssv;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.cmnd = cmnd;
       this.malop = malop;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public Serializable getHoten() {
        return this.hoten;
    }
    
    public void setHoten(Serializable hoten) {
        this.hoten = hoten;
    }
    public Serializable getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(Serializable gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getMalop() {
        return this.malop;
    }
    
    public void setMalop(String malop) {
        this.malop = malop;
    }




}


