package entities;
// Generated Jun 19, 2020 9:15:53 PM by Hibernate Tools 3.6.0



/**
 * Tk generated by hbm2java
 */
public class Tk  implements java.io.Serializable {


     private String mssv;
     private String mk;

    public Tk() {
    }

	
    public Tk(String mssv) {
        this.mssv = mssv;
    }
    public Tk(String mssv, String mk) {
       this.mssv = mssv;
       this.mk = mk;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getMk() {
        return this.mk;
    }
    
    public void setMk(String mk) {
        this.mk = mk;
    }




}


