IF DB_ID('QLSV') IS NOT NULL
	DROP DATABASE QLSV 
GO
CREATE DATABASE QLSV
GO
USE QLSV
CREATE TABLE SINHVIEN
(
	STT INT,
	MSSV CHAR(10),
	HOTEN NVARCHAR(30),
	GIOITINH NVARCHAR(10),
	CMND CHAR(10),
	MALOP CHAR(10)
	CONSTRAINT PK_SINHVIEN
	PRIMARY KEY(MSSV)
)
