/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import DAO.LOPDSSVDAO;
import DAO.SVDAO;
import entities.LopDssv;
import entities.LopDssvId;
import entities.SinhVien;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Long
 */
public class DSLOP extends javax.swing.JFrame {

    /**
     * Creates new form DSLOP
     * @param MaLop
     */
    public DSLOP(String MaLop) {
        initComponents();
        jLabel1.setText("DS LỚP "+MaLop);
        SVDAO svdao=new SVDAO();
        List<SinhVien> dssv= svdao.layDSSV_MaLop(MaLop);
        int i=0;
        Vector vctheader =new Vector();
        vctheader.add("STT");
        vctheader.add("MSSV");
        vctheader.add("Họ Tên");
        vctheader.add("Giới Tính");
        vctheader.add("CMND");
        Vector vctdata=new Vector();
        for (SinhVien sv :dssv)
        {
            i++;
            Vector vctrow=new Vector();
            vctrow.add(i);
            vctrow.add(sv.getMssv());
            vctrow.add(sv.getName());
            vctrow.add(sv.getSex());
            vctrow.add(sv.getCmnd());
            vctdata.add(vctrow);
        }
        tabledssv.setModel(new DefaultTableModel(vctdata,vctheader));
    }
    public DSLOP(String MaLop,String MaMon) {
        initComponents();
        LopDssvId Id=new LopDssvId(MaLop,MaMon,"");
        jLabel1.setText("DS LỚP "+MaLop+"-"+MaMon);
        List<LopDssv> ds_lopdssv=LOPDSSVDAO.layDSSV_ID(Id);
        Vector<SinhVien> dssv=new Vector<SinhVien>();
        for (LopDssv lopdssv: ds_lopdssv)
        {
            dssv.add(SVDAO.find(lopdssv.getId().getMssv()));
        }
        int i=0;
        Vector vctheader =new Vector();
        vctheader.add("STT");
        vctheader.add("MSSV");
        vctheader.add("Họ Tên");
        vctheader.add("Giới Tính");
        vctheader.add("CMND");
        Vector vctdata=new Vector();
        for (SinhVien sv :dssv)
        {
            i++;
            Vector vctrow=new Vector();
            vctrow.add(i);
            vctrow.add(sv.getMssv());
            vctrow.add(sv.getName());
            vctrow.add(sv.getSex());
            vctrow.add(sv.getCmnd());
            vctdata.add(vctrow);
        }
        tabledssv.setModel(new DefaultTableModel(vctdata,vctheader));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledssv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DS LỚP");

        tabledssv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "MSSV", "Họ tên", "Giới tính", "CMND"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabledssv);
        if (tabledssv.getColumnModel().getColumnCount() > 0) {
            tabledssv.getColumnModel().getColumn(0).setMinWidth(50);
            tabledssv.getColumnModel().getColumn(0).setMaxWidth(50);
            tabledssv.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSLOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSLOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSLOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSLOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new DSLOP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabledssv;
    // End of variables declaration//GEN-END:variables

    
}
