/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import DAO.SVDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Long
 */
public class giaovu extends javax.swing.JFrame {

    /**
     * Creates new form giaovu
     */
    public giaovu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Import = new javax.swing.JButton();
        addSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GIÁO VỤ");

        Import.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Import.setText("Import DSSV");
        Import.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportMouseClicked(evt);
            }
        });

        addSV.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        addSV.setText("Thêm SV");
        addSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSVMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Import, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Import)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSV)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportMouseClicked
        //arrayStudent array=new arrayStudent();
        //array.setA(array.getCsv().readCsvFile());
        //giaovu_browser browser=new giaovu_browser();
        //browser.setVisible(true);
       //this.add(browser);
       String Malop=JOptionPane.showInputDialog(this,"LỚP: ","NHẬP MÃ LỚP",1);
       String diachi=JOptionPane.showInputDialog(this,"File csv: ","NHẬP ĐỊA CHỈ FILE CSV",1);
       arrayStudent array=new arrayStudent();
       if (Malop !=null && diachi !=null)
       {
        array.setA(array.getCsv().readCsvFile(diachi));
       }
       for (int i=0;i<array.getA().size();i++)
       {
           array.getA().get(i).setMalop(Malop);
           SVDAO svdao=new SVDAO();
           boolean kq = svdao.themSV(array.getA().get(i));
       }
    }//GEN-LAST:event_ImportMouseClicked

    private void addSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSVMouseClicked
        String Malop=JOptionPane.showInputDialog(this,"LỚP: ","NHẬP SINH VIÊN",1);
        String Mssv=JOptionPane.showInputDialog(this,"MSSV: ","NHẬP SINH VIÊN",1);
        String Name=JOptionPane.showInputDialog(this,"TÊN: ","NHẬP SINH VIÊN",1);
        String Cmnd=JOptionPane.showInputDialog(this,"CMND: ","NHẬP SINH VIÊN",1);
        Object[] selections={"Nam","Nữ"};
        Object Sx=JOptionPane.showInputDialog(this,"GIỚI TÍNH:","NHẬP SINH VIÊN",1,null,selections,selections[0]);
        String Sex = null;
        if (Sx != null)
            Sex=Sx.toString();
        Student st=new Student();
        if (Malop !=null && Mssv !=null && Name !=null && Cmnd !=null && Sex!=null)
        {
            st.setMalop(Malop);
            st.setMssv(Mssv);
            st.setName(Name);
            st.setCmnd(Cmnd);
            st.setSex(Sex);
            SVDAO svdao=new SVDAO();
           boolean kq = svdao.themSV(st);
           JOptionPane.showMessageDialog(this, "THÊM SV THÀNH CÔNG");
        }
        else JOptionPane.showMessageDialog(this, "THÊM SV THẤT BẠI");
 
    }//GEN-LAST:event_addSVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaovu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaovu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaovu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaovu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giaovu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Import;
    private javax.swing.JButton addSV;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
